name: Merge to main workflows

on:
  push:
    branches:
      - main

jobs:
  deploy-to-gh-pages:
    runs-on: ubuntu-latest
    steps:
      # checkout to the commit that has been pushed
      - uses: actions/checkout@v4
        with:
          submodules: true  # 테마가 submodule로 있을 경우를 위해
          fetch-depth: 0    # 전체 git 히스토리 필요

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3.0.0
        with:
          hugo-version: 'latest'
          extended: true

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Setup Hugo Modules and Install Dependencies
        run: |
          hugo mod get -u
          hugo mod tidy
          hugo mod npm pack
          npm install

      - name: Build and Check
        run: |
          hugo -D --minify
          echo "=== Checking public directory structure ==="
          ls -la public/
          echo "=== Checking public directory contents ==="
          find public/ -type f

      # push the generated content into the `gh-pages` branch.
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./public
          full_commit_message: ${{ github.event.head_commit.message }}
          enable_jekyll: false
          force_orphan: true